" symlink ~/.vimrc to the path of this file

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' } " Fuzzy file searching
Plug 'junegunn/fzf.vim' " Grepping
Plug 'scrooloose/nerdtree' " Filetree explorer
Plug 'tpope/vim-fugitive' " Git blame
Plug 'tpope/vim-surround' " Easy quotes/parenthesizing
Plug 'tomtom/tcomment_vim' " Comment toggling
Plug 'AndrewRadev/splitjoin.vim' " Quick toggling of single- and multi- line blocks
Plug 'Valloric/YouCompleteMe' " Autocomplete

call plug#end()
" ============================================================================
set number                          " Show line numbers
set nowrap                          " Do not wrap lines
set noswapfile                      " Disable creation of *.swp files
set tabstop=2                       " Two-space tabs
set shiftwidth=2                    " Number of spaces to use in each autoindent step
set softtabstop=2
set smarttab                        " Use shiftwidth and softtabstop to insert or delete (on <BS>) blanks
set expandtab
set autoindent                      " Keep the indent when creating a new line
set smartindent
set smarttab
set incsearch                       " Find the next match as we type the search
set hlsearch                        " Highlight searches by default
set ignorecase                      " Ignore case when searching...
set smartcase                       " ...unless we type a capital
set guifont=Menlo\ Regular:h18

let mapleader=","

colorscheme jellybeans
" ============================================================================
" Window navigation can be done with just Ctrl+direction(h,j,k,l)
nnoremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-l> <C-w>l
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-j> <C-w>j

" `vv` for vertical split, `ss` for horizontal split
nnoremap <silent> vv <C-w>v
nnoremap <silent> ss <C-w>s

" Fuzzy file search via <Leader>t; search in buffers via <Leader>b
nnoremap <silent> <Leader>t :FZF<cr>
nnoremap <silent> <Leader>b :Buffers<cr>

" <Leader>ws removes trailing whitespace
nnoremap <silent> <Leader>ws :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>

" `sj` to toggle single-line block -> multi-line block, `sk` to toggle multi-line -> single line
nmap sj :SplitjoinSplit<cr>
nmap sk :SplitjoinJoin<cr>

" Term search via <Leader>gg
map <silent> <Leader>gg :Ag<cr>

" Shift+k to grep for the word under the cursor
nnoremap <silent> K :Ag <C-R><C-W><CR>

" Leader+k to search/highlight the word under the cursor, within the current file
nnoremap <silent> <Leader>k *

" clear highlighting via //
map <silent> // :nohlsearch<CR>

" Leader jm|jc|jv to fuzzy file search within models, controllers, or views
map <Leader>jm :FZF app/models<CR>
map <Leader>jc :FZF app/controllers<CR>
map <Leader>jv :FZF app/views<CR>

" Leader+ff to fuzzy file search the word under the cursor ("find-file")
nnoremap <Leader>ff :FzfTagsCurrWord<CR>
command! FzfTagsCurrWord call s:FzfTagsCurrWord()
function! s:FzfTagsCurrWord()
  call fzf#vim#tags(expand('<cword>'))
endfunction

" copy current filename (cf: fullpath, cr: relative path, cn: filename) into system clipboard
nnoremap <silent> <Leader>cf :let @* = expand("%:~")<CR>
nnoremap <silent> <Leader>cr :let @* = expand("%")<CR>
nnoremap <silent> <Leader>cn :let @* = expand("%:t")<CR>

" Use numbers to pick the tab you want (like iTerm)
map <silent> <D-1> :tabn 1<cr>
map <silent> <D-2> :tabn 2<cr>
map <silent> <D-3> :tabn 3<cr>
map <silent> <D-4> :tabn 4<cr>
map <silent> <D-5> :tabn 5<cr>
map <silent> <D-6> :tabn 6<cr>
map <silent> <D-7> :tabn 7<cr>
map <silent> <D-8> :tabn 8<cr>
map <silent> <D-9> :tabn 9<cr>

command! Q :q
command! W :w
" ============================================================================
" Make nerdtree look nice
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let g:NERDTreeWinSize = 30

" Disable the scrollbars (NERDTree)
set guioptions-=r
set guioptions-=L

" Disable the macvim toolbar
set guioptions-=T

nnoremap <silent> <Leader>r :NERDTreeRefresh<cr>

" Opens NERDTree, expose current file with Ctrl + \ (backslash)
" calls NERDTreeFind if
"   + NERDTree is active,
"   + current window contains a modifiable file
"   + we're not in vimdiff

function! OpenNerdTree()
  if &modifiable && strlen(expand('%')) > 0 && !&diff
    NERDTreeFind
  else
    NERDTreeToggle
  endif
endfunction
nnoremap <silent> <C-\> :call OpenNerdTree()<CR>
" ============================================================================
" Find the related spec for open ruby files, and vice-versa
function! s:RelatedSpec()
  let l:fullpath = expand("%:p")
  let l:filepath = expand("%:h")
  let l:fname = expand("%:t")
  let l:filepath_without_app = substitute(l:filepath, "app/", "", "")
  let l:filepath_without_app = substitute(l:filepath_without_app, "assets/", "", "")

  " Possible names for the spec/test for the file we're looking at
  let l:test_names = [substitute(l:fname, ".rb$", "_spec.rb", ""), substitute(l:fname, ".rb$", "_test.rb", ""), substitute(l:fname, ".js$", "_spec.js", ""), substitute(l:fname, ".jsx$", "_spec.js", ""), substitute(l:fname, ".jsx$", "_spec.jsx", "")]

  " Possible paths
  let l:test_paths = ["spec", "fast_spec", "test"]

  for test_name in l:test_names
    for path in l:test_paths
      let l:spec_path = path . "/" . l:filepath_without_app . "/" . test_name
      let l:full_spec_path = substitute(l:fullpath, l:filepath . "/" . l:fname, l:spec_path, "")
      if filereadable(l:spec_path)
        return l:full_spec_path
      end
    endfor
  endfor
endfunction

" Find the file being tested when looking at a spec
function! s:FileRelatedToSpec()
  let l:fullpath = expand("%:p")
  let l:filepath = expand("%:h")
  let l:fname = expand("%:t")

  let l:related_file = substitute(l:filepath, "fast_spec/", "", "")
  let l:related_file = substitute(l:related_file, "spec/", "", "")

  let l:related_file_names = [substitute(l:fname, "_spec.rb$", ".rb", ""), substitute(l:fname, "_spec.js$", ".js", ""), substitute(l:fname, "_spec.js$", ".jsx", ""), substitute(l:fname, "_spec.jsx$", ".jsx", "")]

  for related_file_name in l:related_file_names
    let l:full_file_path = substitute(l:fullpath, l:filepath . "/" . l:fname, "app/" . l:related_file . "/" . related_file_name, "")
    if match(l:full_file_path, "javascripts") != -1
      let l:full_file_path = substitute(l:full_file_path, "app/", "app/assets/", "")
    end
    if filereadable(l:full_file_path)
      return l:full_file_path
    end
  endfor
endfunction

" If looking at a regular file, find the related spec
" If looking at a spec, find the related file
function! s:RelatedSpecOrFile()
  let l:fname = expand("%:t")
  if match(l:fname, "_spec") != -1
    let l:result = s:FileRelatedToSpec()
  else
    let l:result = s:RelatedSpec()
  endif

  return l:result
endfunction

function! s:RelatedSpecOpen()
  let l:spec_path = s:RelatedSpecOrFile()
  if filereadable(l:spec_path)
    execute ":e " . l:spec_path
  endif
endfunction

function! s:RelatedSpecVOpen()
  let l:spec_path = s:RelatedSpecOrFile()
  if filereadable(l:spec_path)
    execute ":botright vsp " . l:spec_path
  endif
endfunction

command! RelatedSpecVOpen call s:RelatedSpecVOpen()
command! RelatedSpecOpen call s:RelatedSpecOpen()

nnoremap <silent> <C-s> :RelatedSpecVOpen<CR>
nnoremap <silent> ,<C-s> :RelatedSpecOpen<CR>
" ============================================================================
